### ISSUE TITLE
Conditional compilation of statics fails build

### ISSUE THREAD

**Issue by DoumanAsh** [japaric/cortex-m-rtfm#110]
This is a minor issue, but currently if I try to put `#cfg` onto declaration of static variable at the start of function within `#[app]`, it will fail to compile as `static mut &'a T` is generated unconditionally.

One of the use cases would be conditionally initialize logger instead of using noop logger to save a bit of space(e.g. https://github.com/DoumanAsh/2B/blob/master/src/main.rs#L27-L41)

I didn't look into rtfm macros yet, but I imagine it should be possible to analyze what `#cfg` is used by static and apply the same to generated reference.

**Comment by japaric** [comment]
#112 will fix this for idle, init and task. rust-embedded/cortex-m-rt#159 fixed this for exception and interrupt

**Comment by DoumanAsh** [comment]
Thanks
