### ISSUE TITLE
book new.md example references a file that doesn't exist

### ISSUE THREAD

**Issue by x37v** [japaric/cortex-m-rtfm#124]
`https://github.com/japaric/cortex-m-rtfm/blob/master/book/src/by-example/new.md`

indicates:
```
curl \
    -L https://github.com/japaric/cortex-m-rtfm/raw/v0.4.0/examples/init.rs \
    > src/main.rs
```

but that file doesn't exist.

I would submit a PR but I'm not sure which file it should target. Maybe there should be a *0.4.0* tag and then reference that?

**Comment by TeXitoi** [comment]
This curl is working here. @x37v can you confirm that it's now working?

**Comment by x37v** [comment]
@TeXitoi looks good here.
