### ISSUE TITLE
Set device.DBG.cr.dbg_sleep to 1 when using wfi in the idle task.

### ISSUE THREAD

**Issue by nraynaud** [japaric/cortex-m-rtfm#131]
I was struggling to flash my device with openocd after I started using RTFM while googling I found this message:
https://www.jsykora.info/2014/10/error-jtag-status-contains-invalid-mode-value-communication-failure-solved/

adding this at the top of my init seems to have helped:
```    
	#[init(schedule = [toggle])] 
	unsafe fn init() {
        let dbg = device.DBG;
        dbg.cr.modify(|_, w| w.dbg_sleep().set_bit());
    }
```

**Comment by nraynaud** [comment]
I am wrong, this has to be done in the debugger when we need it, this re-activate a clock.

**Comment by japaric** [comment]
>  let dbg = device.DBG;

This is device specific and can't really be done in rtfm. It could be the case that the device does not have a DBG peripheral; or it may not be named like that; or its registers / bit fields may be named differently; or the svd file may not contain bitfield information.

**Comment by nraynaud** [comment]
I see.
