### ISSUE TITLE
Tracking release of 0.5.0

### ISSUE THREAD

**Issue by jacobrosenthal** [japaric/cortex-m-rtfm#215]
Anything left to be done?

I believe https://github.com/nrf-rs/nrf52-hal/pull/102 Needs this bumped to 0.5.0 to move forward

**Comment by japaric** [comment]
> Tracking release of 0.5.0

The [v0.5.0 milestone](https://github.com/japaric/cortex-m-rtfm/milestone/4) is tracking the release. All related RFCs have been accepted and implemented. Only the documentation needs to be updated before a (pre-)release.

I'm going to close this issue in favor of the milestone.
