### ISSUE TITLE
Switch to some Cortex-M0 device crate

### ISSUE THREAD

**Issue by jonas-schievink** [japaric/cortex-m-rtfm#45]
Currently, the examples build against the stm32f103xx crate, which is for a family of Cortex-M3 microcontrollers. Cortex-M3 implements armv7, and due to recent changes in svd2rust such a crate can not be compiled for the `thumbv6m-none-eabi` target. While it's generally nonsensical to do that, it prevents us from building the examples in this repo for an armv6 target.

In #43, I've made the tests pass by replacing the linker for the `thumbv6m-none-eabi` target with `true` - a pretty horrible hack. The proper solution for this would be to switch to a device crate for some Cortex-M0 microcontroller, propably in the stm32f0 family.

<sub>NB: It makes even less sense to compile an M0 device crate for armv7, but it currently works.</sub>

**Comment by japaric** [comment]
As of v0.4.x we are using the `lm3s6965` device crate to test the `thumbv6m-none-eabi` target. It's not a Cortex-M3 device per se but the crate has been tweaked to generate valid binaries that run on QEMU when compiled for `thumbv6m-none-eabi`.
