### ISSUE TITLE
Name collision on task / resource / peripheral name.

### ISSUE THREAD

**Issue by jothan** [japaric/cortex-m-rtfm#68]
I had a bit of trouble with a task named RTC that uses a resource named RTC that is a peripheral named RTC. I am using RTFM 0.3.1.

The workaround I applied was to rename the resource RTC_R and not import the peripheral name directly.

The main problem seems to revolve around the fact that the task and resource are simply prefixed by a single underscore, resulting in a collision.

Conceptually, do you see tasks as living in a different namespace than resources ? Is there any other way similar use cases could be made simpler ?

```
app! {
    device: stm32f103xx,

    resources: {
        static RTC_R: stm32f103xx::RTC;
        static PWR: PWR;
        static SCB: SCB;
    },

    tasks: {
        RTC: {
            path: isr_rtc,
            resources: [RTC_R, PWR, SCB],
        },
    },
}

```

**Comment by japaric** [comment]
Most of the code generated by the v0.4.x of the `app` macro is pseudo-hygienic to minimize the pollution of the user code namespaces. The only names that the macro will use are in the module namespace; the macro will generate one module per task and also `init`, `idle` and `resources` modules.

Giving the same name to a resource and to a task should be fine now. If you encounter any name collision please open a new issue.
