### ISSUE TITLE
quickstart/link other required reading

### ISSUE THREAD

**Issue by FlorianUekermann** [japaric/cortex-m-rtfm#70]
The original issue was about some build errors. I now realize that I missed some important pieces of documentation. My entry point into this was the cortex-m-rtfm package, whose documentation doesn't reference some other important parts. Maybe a cortex-m-rtfm-quickstart, or just a link or two would help others out are not familiar your related work.

**Comment by japaric** [comment]
This crate now has a [book](https://japaric.github.io/cortex-m-rtfm/book/) and both the README in this repository and the [crates.io] landing page link to the book. If you think some topic is missing please open an issue requesting it.

[crates.io]: https://crates.io/crates/cortex-m-rtfm/0.4.0-beta.1
