### ISSUE TITLE
Provide reset vector

### ISSUE THREAD

**Issue by bofh** [japaric/cortex-m-rtfm#77]
A standard trick to avoid deinitialization of controller's peripherals one by one before jump to bootloader is to set a cookie somewhere in RAM unaffected by reset, perform reset of the chip and check that cookie in reset vector jumping to bootloader if set. Right now quite a lot is happening before call to init, so it's possible for that code to interfere with bootloader call. It would be nice to have an ability to run user code just before anything else for such use case.

Another approach would be adding RCC deinitialization and peripheral reset functions to HAL.

See also: japaric/stm32f30x-hal#24

**Comment by japaric** [comment]
You can run code before `init` using [`cortex_m_rt::pre_init`](https://docs.rs/cortex-m-rt-macros/0.1.3/cortex_m_rt_macros/attr.pre_init.html). If you think a feature is needed in RTFM to support your use case please a new issue with details about what you'll like to see.
