### ISSUE TITLE
minimal example fails to build

### ISSUE THREAD

**Issue by timbod7** [japaric/cortex-m-rtfm#90]
I've copied

https://github.com/japaric/cortex-m-rtfm/blob/master/examples/zero-tasks.rs

 into my own repo, and adapted it to use the stm32f4 crate. The resulting code is here: 

https://github.com/timbod7/rust-stm32f4-examples/blob/master/minimal-rtfm/src/main.rs

this fails to build with a suprising (to me) error:

```
   Compiling minimal-rtfm v0.0.1 (file:///home/timd/personal/projects/stm-f4/rust-stm32f4-examples/minimal-rtfm)      
error: function is never used: `init`
  --> src/main.rs:28:1
   |
28 | fn init(p: init::Peripherals) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: function is never used: `idle`
  --> src/main.rs:41:1
   |
41 | fn idle() -> ! {
   | ^^^^^^^^^^^^^^
```

I would have expected these functions to be referenced from the code generated by the `app!` macro.

What am I doing wrong?

**Comment by timbod7** [comment]
Not sure I understand what you mean by "use #87".

I've simplified the dependendecies, and use cortex-m-rt 0.3:

```
[dependencies.stm32f4]
version = "0.2.3"
features = ["stm32f407", "rt"]

[dependencies.cortex-m]
version = "0.5.7"

[dependencies.cortex-m-rt]
version = "0.3"

[dependencies]
cortex-m-rtfm = "0.3.4"

[dependencies.panic-abort]
version = "0.3.0"

**Comment by TeXitoi** [comment]
stm32f4 v0.2.3 depends on cortex-m v0.5.

I mean you can use the branch of the pull request:
```
cortex-m-rtfm = { git = "https://github.com/ykomatsu/cortex-m-rtfm", branch = "update" }
```

**Comment by timbod7** [comment]
Thanks so much! That approach did eventually work.

**Comment by TeXitoi** [comment]
Welcome.
